sudo: required

services:
  - docker
  
script:
- docker run --rm -v $(pwd):/root/sources -w /root/sources -e BINTRAY_USER="${BINTRAY_USER}" -e BINTRAY_APIKEY="${BINTRAY_APIKEY}" maven:3.5-jdk-8 ./scripts/travis.sh
