-- MySQL Script generated by MySQL Workbench
-- Fri Dec 15 13:35:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OML
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OML
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OML` DEFAULT CHARACTER SET utf8 ;
USE `OML` ;

-- -----------------------------------------------------
-- Table `OML`.`TerminologyGraphs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OML`.`TerminologyGraphs` (
  `uuid` BINARY(16) NOT NULL,
  `kind` VARCHAR(32) NULL,
  `IRI` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OML`.`Concepts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OML`.`Concepts` (
  `uuid` BINARY(16) NOT NULL,
  `tbox_uuid` BINARY(16) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_Concepts_TerminologyGraphs_idx` (`tbox_uuid` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  CONSTRAINT `fk_Concepts_TerminologyGraphs`
    FOREIGN KEY (`tbox_uuid`)
    REFERENCES `OML`.`TerminologyGraphs` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OML`.`ConceptSpecializationAxioms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OML`.`ConceptSpecializationAxioms` (
  `uuid` BINARY(16) NOT NULL,
  `tbox_uuid` BINARY(16) NOT NULL,
  `superConcept_uuid` BINARY(16) NOT NULL,
  `subConcept_uuid` BINARY(16) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_ConceptSpecializationAxioms_TerminologyGraphs1_idx` (`tbox_uuid` ASC),
  INDEX `fk_ConceptSpecializationAxioms_ConceptSpecializationAxioms1_idx` (`superConcept_uuid` ASC),
  INDEX `fk_ConceptSpecializationAxioms_ConceptSpecializationAxioms2_idx` (`subConcept_uuid` ASC),
  CONSTRAINT `fk_ConceptSpecializationAxioms_TerminologyGraphs1`
    FOREIGN KEY (`tbox_uuid`)
    REFERENCES `OML`.`TerminologyGraphs` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConceptSpecializationAxioms_ConceptSpecializationAxioms1`
    FOREIGN KEY (`superConcept_uuid`)
    REFERENCES `OML`.`ConceptSpecializationAxioms` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConceptSpecializationAxioms_ConceptSpecializationAxioms2`
    FOREIGN KEY (`subConcept_uuid`)
    REFERENCES `OML`.`ConceptSpecializationAxioms` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OML`.`TerminologyExtensionAxioms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OML`.`TerminologyExtensionAxioms` (
  `uuid` BINARY(16) NOT NULL,
  `tbox_uuid` BINARY(16) NOT NULL,
  `extendedTerminologyIRI` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_TerminologyExtensionAxioms_TerminologyGraphs1_idx` (`tbox_uuid` ASC),
  CONSTRAINT `fk_TerminologyExtensionAxioms_TerminologyGraphs1`
    FOREIGN KEY (`tbox_uuid`)
    REFERENCES `OML`.`TerminologyGraphs` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OML`.`AnnotationProperties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OML`.`AnnotationProperties` (
  `uuid` BINARY(16) NOT NULL,
  `IRI` VARCHAR(64) NULL,
  `abbrevIRI` VARCHAR(32) NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OML`.`AnnotationPropertyValues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OML`.`AnnotationPropertyValues` (
  `uuid` BINARY(16) NOT NULL,
  `subject_uuid` BINARY(16) NOT NULL,
  `property_uuid` BINARY(16) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_AnnotationPropertyValues_Concepts1_idx` (`subject_uuid` ASC),
  INDEX `fk_AnnotationPropertyValues_AnnotationProperties1_idx` (`property_uuid` ASC),
  CONSTRAINT `fk_AnnotationPropertyValues_Concepts1`
    FOREIGN KEY (`subject_uuid`)
    REFERENCES `OML`.`Concepts` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnnotationPropertyValues_AnnotationProperties1`
    FOREIGN KEY (`property_uuid`)
    REFERENCES `OML`.`AnnotationProperties` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
